change-template: '- $TITLE (@$AUTHOR, PR #$NUMBER)'
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'âš ï¸ BC Breaks'
    labels:
      - 'BC break'
      - 'BCbreak'
      - 'bcbreak'
  - title: 'ğŸ‘‹ï¸ VyÅ¾aduje pozornost nebo ruÄnÃ­ zÃ¡sah'
    labels:
      - 'warning'
      - 'Warning'
  - title: 'ğŸ™ Obsahuje migrace'
    labels:
      - 'migrations'
      - 'Migrations'
  - title: 'ğŸš€ Features'
    collapse-after: 8
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    collapse-after: 8
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ§° Chore'
    collapse-after: 8
    label:
      - 'chore'
      - 'Chore'
      - 'maintenance'
  - title: ':ghost: Byla povÃ½Å¡ena verze chart'
    collapse-after: 8
    label:
      - 'chart'
      - 'Chart'
exclude-contributors:
  - 'action-user'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
